spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:personDB
        password: password
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
